### ISSUE TITLE
How to custom style

### ISSUE THREAD

**Issue by maxiplay** [PolymerElements/iron-collapse#45]
I want to set the overflow to hidden but no customizable property is available

**Comment by valdrinkoshi** [comment]
you can apply the style to all your `iron-collapse` like this:
```css
iron-collapse {
  overflow: hidden;
}
```
